
package com.app;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SOAPEndpointService", targetNamespace = "http://app.com/", wsdlLocation = "http://127.0.0.1:8081/myservice?wsdl")
public class SOAPEndpointService
    extends Service
{

    private final static URL SOAPENDPOINTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SOAPENDPOINTSERVICE_EXCEPTION;
    private final static QName SOAPENDPOINTSERVICE_QNAME = new QName("http://app.com/", "SOAPEndpointService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:8081/myservice?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SOAPENDPOINTSERVICE_WSDL_LOCATION = url;
        SOAPENDPOINTSERVICE_EXCEPTION = e;
    }

    public SOAPEndpointService() {
        super(__getWsdlLocation(), SOAPENDPOINTSERVICE_QNAME);
    }

    public SOAPEndpointService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SOAPENDPOINTSERVICE_QNAME, features);
    }

    public SOAPEndpointService(URL wsdlLocation) {
        super(wsdlLocation, SOAPENDPOINTSERVICE_QNAME);
    }

    public SOAPEndpointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SOAPENDPOINTSERVICE_QNAME, features);
    }

    public SOAPEndpointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPEndpointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SOAPEndpoint
     */
    @WebEndpoint(name = "SOAPEndpointPort")
    public SOAPEndpoint getSOAPEndpointPort() {
        return super.getPort(new QName("http://app.com/", "SOAPEndpointPort"), SOAPEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SOAPEndpoint
     */
    @WebEndpoint(name = "SOAPEndpointPort")
    public SOAPEndpoint getSOAPEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://app.com/", "SOAPEndpointPort"), SOAPEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SOAPENDPOINTSERVICE_EXCEPTION!= null) {
            throw SOAPENDPOINTSERVICE_EXCEPTION;
        }
        return SOAPENDPOINTSERVICE_WSDL_LOCATION;
    }

}
